version: "3.9"

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - internal_network

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - api
    ports:
      - "81:80"
    networks:
      - internal_network

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=pms_db
      - POSTGRES_USER=pms_user
      - POSTGRES_PASSWORD=pms_pass
    ports:
      - "5432:5432"  # ✅ necessário para permitir acesso via localhost
    volumes:
      - pgdata:/var/lib/postgres/data
    networks:
      - internal_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "pms_user", "-d", "pms_db"]
      interval: 10s
      retries: 5

volumes:
  pgdata:

networks:
  internal_network:
    driver: bridge
